version: '3'
services:
  pwc-db:
    image: postgres
    container_name: pwc-db
    ports:
      - '5432:5432'
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres-db:/var/lib/postgresql/data
  pwc-backend:
    stdin_open: true
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    container_name: pwc-backend
    depends_on:
      - pwc-db
    ports:
      - '8000:8000'
    restart: always
  pwc-web:
    build:
      context: ./packages/web
      dockerfile: Dockerfile
    container_name: pwc-web
    depends_on:
      - pwc-backend
    ports:
      - '3000:3000'
    restart: always

volumes:
  postgres-db:
